/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.13.4.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Hub.types";
import * as _1 from "./Hub.client";
import * as _2 from "./Nft.types";
import * as _3 from "./Nft.client";
export namespace contracts {
  export const Hub = { ..._0,
    ..._1
  };
  export const Nft = { ..._2,
    ..._3
  };
}